"""Render the profile database data dictionary.

Split out of generate_schema_contract.py so the large markdown template does not
have to be escaped inside that module. Imported and called from there.
"""

from __future__ import annotations

import re

RELATION_RE = re.compile(r"(?P<relation>[a-z_]+\.[a-z_]+)\s*(?P<detail>\([^)]*\))?")

INTRO = """
This is the complete reference for every physical table in the profile database:
what the table is for, every column with its type and definition, and which
build step populates it.

**How to read "Populated by".** The profile database is not loaded by one job.
It is built in ordered steps (see
[PROFILE_DATABASE_LINEAGE.md](PROFILE_DATABASE_LINEAGE.md)), and most tables are
written by several of them: an early step creates the row, later enrichment
steps fill columns that need other data to exist first. Every step that writes
the table is listed, in build order. Where a step writes only certain columns,
those columns are named in parentheses.

**Two modes write these tables.** `rebuild` recreates everything from source.
`refresh` runs nightly and MERGEs only the profiles that changed in the lookback
window. A column filled by rebuild enrichment is not necessarily recomputed on
every refresh.

**Sensitive fields.** Columns flagged sensitive in the DDL are redacted from
`profile_current_safe`, the default consumer surface. Use `profile_current` only
with approved access.

**Source of truth.** This file is generated from the DDL and the `WRITES:`
headers in the active SQL. If a definition here looks wrong, fix the comment in
`sql/profile_database_ddl.sql` and regenerate -- do not edit this file.
"""


def build_table_writers(lineage_rows, relation_re=RELATION_RE):
    """Map each physical table to the ordered build steps that write it."""
    writers: dict[str, list[str]] = {}
    for row in lineage_rows:
        writes = row.get("writes") or ""
        if not writes or writes.startswith("Unknown"):
            continue
        for match in relation_re.finditer(writes):
            relation = match.group("relation")
            detail = (match.group("detail") or "").strip()
            entry = "`{}`".format(row["step"])
            if detail:
                entry += " {}".format(detail)
            writers.setdefault(relation, [])
            if entry not in writers[relation]:
                writers[relation].append(entry)
    return writers


MIRROR_TABLES = {
    "profile_ops.profile_core_snapshot": "profile_data.profile_core",
}

# Columns whose meaning is identical everywhere they appear. Documented once
# here rather than repeated as a DDL comment on every table.
COMMON_COLUMNS = {
    "bn_id": "FK to profile_core.bn_id -- the stable identity-graph person ID.",
    "loaded_at": "When this row was last written by the build.",
    "created_at": "Row creation timestamp.",
    "updated_at": "Row last-update timestamp.",
    "first_seen": "Earliest observation of this fact.",
    "last_seen": "Most recent observation of this fact.",
    "sort_order": "Display ordering hint for reference/dictionary values.",
    "is_active": "FALSE retires the row without deleting it.",
    "build_id": "FK to profile_ops.profile_build_runs.build_id.",
    "started_at": "When this step or run began.",
    "completed_at": "When this step or run finished.",
    "site_domain": "Site the activity or record belongs to (e.g. myasthenia-gravis.com).",
}


def _fill_definitions(columns):
    """Inherit definitions for mirror tables and well-known shared columns."""
    for relation, source in MIRROR_TABLES.items():
        if relation not in columns or source not in columns:
            continue
        source_defs = {c["name"]: c["comment"] for c in columns[source] if c["comment"]}
        for col in columns[relation]:
            if not col["comment"] and col["name"] in source_defs:
                col["comment"] = source_defs[col["name"]] + " _(mirrored)_"
    for relation, cols in columns.items():
        for col in cols:
            if not col["comment"] and col["name"] in COMMON_COLUMNS:
                col["comment"] = COMMON_COLUMNS[col["name"]]
    return columns


def render(
    *,
    columns,
    lineage_rows,
    header,
    schema_version,
    production_dataset,
    ops_dataset,
    staging_dataset,
    table_descriptions,
    consumer_order,
    ops_order,
):
    columns = _fill_definitions(columns)
    writers = build_table_writers(lineage_rows)
    out: list[str] = []
    add = out.append

    add(header)
    add("# Profile Database Data Dictionary\n\n")
    add("**Version:** `{}`\n".format(schema_version))
    add(
        "**Datasets:** `{}`, `{}`, `{}`\n".format(
            production_dataset, ops_dataset, staging_dataset
        )
    )
    add(
        "**Generated from:** [sql/profile_database_ddl.sql]"
        "(../sql/profile_database_ddl.sql) plus the active SQL `WRITES:` headers.\n"
    )
    add(INTRO)
    add("\n---\n\n")

    def sort_key(relation):
        dataset, table = relation.split(".", 1)
        if dataset == production_dataset:
            rank = consumer_order.index(table) if table in consumer_order else 999
            return (0, rank, table)
        if dataset == ops_dataset:
            rank = ops_order.index(table) if table in ops_order else 999
            return (1, rank, table)
        return (2, 999, table)

    relations = sorted(columns, key=sort_key)

    add("## Contents\n\n")
    current_ds = None
    for relation in relations:
        dataset, table = relation.split(".", 1)
        if dataset != current_ds:
            current_ds = dataset
            add("\n**`{}`**\n\n".format(dataset))
        anchor = table
        add(
            "- [`{}`](#{}) -- {} columns\n".format(
                table, anchor, len(columns[relation])
            )
        )
    add("\n---\n\n")

    for relation in relations:
        dataset, table = relation.split(".", 1)
        cols = columns[relation]
        add("## {}\n\n".format(table))
        add("**Dataset:** `{}`  \n".format(dataset))
        add(
            "**Description:** {}  \n".format(
                table_descriptions.get(table, "_No description in manifest._")
            )
        )
        add("**Columns:** {}  \n".format(len(cols)))

        steps = writers.get(relation, [])
        if steps:
            add("**Populated by:** {}\n\n".format(", ".join(steps)))
        else:
            add("**Populated by:** _DDL only; no declared writer._\n\n")

        add("| Column | Type | Definition |\n")
        add("|--------|------|------------|\n")
        for col in cols:
            definition = col["comment"].replace("|", "\\|") or "--"
            coltype = col["type"].replace("|", "\\|")
            if col.get("parent"):
                # nested STRUCT/ARRAY field: indent it under the column it belongs to
                name = "&nbsp;&nbsp;↳ `{}`".format(col["name"])
            else:
                name = "`{}`".format(col["name"])
            add("| {} | `{}` | {} |\n".format(name, coltype, definition))
        add("\n")

    return "".join(out)
