#!/usr/bin/env python3
"""
Emit sql/identity_hub_bi_queries.sql and sql/profile_db_bi_queries.sql from the
same lists that build the two BI .docx documents.

Generated rather than hand-written on purpose. The SQL files and the documents
must always agree, and the only way to guarantee that is to build both from one
source: scripts/build_bi_query_docx.py. Edit the queries there; run this and the
docx generator; both outputs move together.

Output contract, so the files run start to finish with no editing:
  * every non-SQL line begins with --
  * every statement ends with a semicolon
  * queries appear in the same order as the documents, which build on each
    other -- the first query in each file is the one everything else assumes

  python scripts/build_bi_query_sql.py
"""

from __future__ import annotations

import importlib.util
import re
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCX_GEN = REPO / "scripts" / "build_bi_query_docx.py"
HUB_OUT = REPO / "sql" / "identity_hub_bi_queries.sql"
PROFILE_OUT = REPO / "sql" / "profile_db_bi_queries.sql"
VERIFIED = "2026-08-20"

RULE_MARKER = "RED::"
BAR = "-- " + "=" * 74


def _load_docx_generator():
    spec = importlib.util.spec_from_file_location("_bi_docx", DOCX_GEN)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_bi_docx"] = mod
    spec.loader.exec_module(mod)
    return mod


def _strip_marker(s: str) -> str:
    return s[len(RULE_MARKER) :] if s.startswith(RULE_MARKER) else s


def _wrap(body: str, width: int = 74, indent: str = "-- ") -> list[str]:
    """Comment-wrap prose. Never emits a bare line, so the file stays runnable."""
    out = []
    for para in body.split("\n\n"):
        para = " ".join(para.split())
        if not para:
            continue
        if out:
            out.append("--")
        out.extend(
            textwrap.wrap(
                para, width=width, initial_indent=indent, subsequent_indent=indent
            )
        )
    return out


def _terminate(sql: str) -> str:
    """Guarantee exactly one trailing semicolon."""
    sql = sql.rstrip().rstrip(";").rstrip()
    return sql + "\n;"


def _header(title: str, subtitle: str, rules, count: int) -> list[str]:
    L = [BAR, f"-- {title.upper()}", BAR]
    L += _wrap(subtitle)
    L.append("--")
    L += _wrap(
        f"{count} queries, in the same order as the document of the same name. "
        "They build on each other -- the first establishes the filter every "
        "later query assumes, so read them in order the first time."
    )
    L.append("--")
    L += _wrap(
        f"Read-only. Verified against production {VERIFIED}. Every statement "
        "ends with a semicolon and every non-SQL line is a -- comment, so the "
        "file runs top to bottom without editing."
    )
    L.append("--")
    L += _wrap(
        "Generated by scripts/build_bi_query_sql.py from the same source as the "
        ".docx. Edit the queries in scripts/build_bi_query_docx.py, not here."
    )
    L.append(BAR)
    L.append("")
    L.append("")
    L.append(BAR)
    L.append("-- BEFORE YOU START -- THE RULES THAT PREVENT WRONG ANSWERS")
    L.append(BAR)
    for i, (heading, body) in enumerate(rules, 1):
        heading = _strip_marker(heading)
        body = _strip_marker(body)
        if i > 1:
            L.append("--")
        L += _wrap(f"{i}. {heading}")
        L += _wrap(body, indent="--    ")
    L.append(BAR)
    return L


def _emit(path: Path, title: str, subtitle: str, rules, queries) -> None:
    lines = _header(title, subtitle, rules, len(queries))
    for name, note, sql in queries:
        name = _strip_marker(name).strip()
        note = _strip_marker(note).strip()
        lines += ["", "", BAR, f"-- {name.upper()}", BAR]
        lines += _wrap(note)
        lines.append("")
        lines.append(_terminate(sql.strip()))
    text = "\n".join(lines).rstrip() + "\n"

    # Contract check: nothing outside a comment or a statement.
    bad = [
        (i, ln)
        for i, ln in enumerate(text.splitlines(), 1)
        if ln.strip()
        and not ln.lstrip().startswith("--")
        and not re.match(r"^[\s\w`(*,.'\"|<>=!+\-/:@\[\]{}%$#?^&~;)]*$", ln)
    ]
    assert not bad, f"non-SQL, non-comment line in {path.name}: {bad[:3]}"

    path.write_text(text, encoding="utf-8", newline="\n")
    stmts = text.count("\n;")
    print(
        f"[OK] Wrote {path.relative_to(REPO)}  ({len(queries)} queries, {stmts} statements)"
    )


def main() -> int:
    g = _load_docx_generator()
    _emit(
        HUB_OUT,
        "Identity hub -- BI query set",
        "The identity graph answers one question: who is this? These queries "
        "cover audience sizing, identifier health and the checks that stop a "
        "count being inflated by bots or by cookie-only records.",
        g.HUB_RULES,
        g.HUB_QUERIES,
    )
    _emit(
        PROFILE_OUT,
        "Profile database -- BI query set",
        "The profile database answers what do we know about them. These "
        "queries cover audience by condition and role, the HCP funnel, "
        "engagement and growth -- each with the rule that stops the number "
        "being quoted wrongly.",
        g.PROFILE_RULES,
        g.PROFILE_QUERIES,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
