#!/usr/bin/env python3
"""
Generate the profile database schema contract + lineage docs from the live repo contract.

Outputs:
  - docs/PROFILE_DATABASE_SCHEMA_CONTRACT.md
  - docs/PROFILE_DATABASE_LINEAGE.md
  - docs/PROFILE_DATABASE_DATA_DICTIONARY.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts import _dictdoc  # noqa: E402
from scripts._ddlparse import parse_columns  # noqa: E402

from shared.profile_database_manifest import (  # noqa: E402
    ACTIVE_SQL_FILES,
    BUILD_STEPS,
    COMPATIBILITY_VIEWS,
    DEFAULT_CONSUMER_VIEW,
    OPS_DATASET,
    OPS_TABLE_GROUPS,
    PHYSICAL_TABLE_GROUPS,
    PRODUCTION_DATASET,
    REBUILD_CANDIDATE_DATASET,
    SCHEMA_VERSION,
    STAGING_DATASET,
    STAGING_TABLE_GROUPS,
    SUPPORTED_VIEWS,
    TABLE_DESCRIPTIONS,
    VIEW_DESCRIPTIONS,
    ordered_subset,
)


DDL = REPO_ROOT / "sql" / "profile_database_ddl.sql"
VIEWS_SQL = REPO_ROOT / "sql" / "profile_database_views.sql"
CONTRACT_OUTPUT = REPO_ROOT / "docs" / "PROFILE_DATABASE_SCHEMA_CONTRACT.md"
LINEAGE_OUTPUT = REPO_ROOT / "docs" / "PROFILE_DATABASE_LINEAGE.md"
DICTIONARY_OUTPUT = REPO_ROOT / "docs" / "PROFILE_DATABASE_DATA_DICTIONARY.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_schema_contract.py - DO NOT EDIT BY HAND -->\n"
    "<!-- Re-generate: python scripts/generate_schema_contract.py -->\n\n"
)

RELATION_RE = re.compile(r"(?P<relation>[a-z_]+\.[a-z_]+)\s*(?P<detail>\([^)]*\))?")
WRITE_LINE_RE = re.compile(r"^\s*--\s*WRITES:\s*(.*)$")
COMMENT_LINE_RE = re.compile(r"^\s*--\s*(.*)$")


FALLBACK_WRITES: dict[str, list[str]] = {
    "sql/profile_database_snapshot_app_fields.sql": [
        "profile_staging.profile_core_app_snapshot",
    ],
    "sql/profile_database_rebuild_scope_all.sql": [
        "profile_staging.refresh_scope_bn_ids",
    ],
    "sql/profile_database_ddl.sql": [
        "DDL only",
    ],
    "sql/profile_database_maintenance.sql": [
        "profile_data.profile_lookup",
        "profile_data.conditions_dict",
        "profile_data.symptoms_dict",
        "profile_data.treatments_dict",
        "profile_data.subtypes_dict",
        "profile_data.dictionary_meta",
        "profile_data.profile_engagement",
        "profile_data.profile_core",
    ],
    "sql/profile_database_views.sql": [
        "profile_data views only",
    ],
    "sql/profile_database_refresh_scope.sql": [
        "profile_staging.refresh_scope_bn_ids",
    ],
    "sql/profile_database_refresh.sql": [
        "profile_data.profile_identifiers",
        "profile_data.profile_core",
        "profile_data.profile_engagement",
        "profile_data.profile_survey_data",
        "profile_data.site_events",
        "profile_data.profile_zero_party",
        "profile_ops.profile_field_changes",
    ],
}


def parse_tables_for_dataset(dataset: str) -> list[str]:
    src = DDL.read_text(encoding="utf-8")
    return [
        match.group(1)
        for match in re.finditer(
            rf"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+{re.escape(dataset)}\.(\w+)",
            src,
            re.IGNORECASE,
        )
    ]


def parse_views() -> list[str]:
    src = VIEWS_SQL.read_text(encoding="utf-8").replace("{view_dataset}", PRODUCTION_DATASET)
    return [
        match.group(1)
        for match in re.finditer(
            r"CREATE\s+OR\s+REPLACE\s+VIEW\s+profile_data\.(\w+)",
            src,
            re.IGNORECASE,
        )
    ]


def flatten_grouped_items(groups: tuple[tuple[str, tuple[str, ...]], ...]) -> list[str]:
    ordered: list[str] = []
    for _, items in groups:
        for item in items:
            if item not in ordered:
                ordered.append(item)
    return ordered


def parse_write_targets(sql_file: str) -> list[str]:
    lines = (REPO_ROOT / sql_file).read_text(encoding="utf-8").splitlines()
    collected: list[str] = []
    in_block = False
    for line in lines[:80]:
        write_match = WRITE_LINE_RE.match(line)
        if write_match:
            in_block = True
            payload = write_match.group(1).strip()
            if payload:
                collected.append(payload)
            continue

        if not in_block:
            continue

        comment_match = COMMENT_LINE_RE.match(line)
        if not comment_match:
            break

        payload = comment_match.group(1).strip()
        if not payload:
            break
        if RELATION_RE.search(payload) or payload.lower().endswith("only"):
            collected.append(payload)
            continue
        break

    if not collected:
        return FALLBACK_WRITES.get(sql_file, [])

    parsed: list[str] = []
    for payload in collected:
        if payload.lower().endswith("only"):
            parsed.append(payload)
            continue
        matches = list(RELATION_RE.finditer(payload))
        if not matches:
            continue
        for match in matches:
            relation = match.group("relation")
            detail = (match.group("detail") or "").strip()
            parsed.append(f"{relation} {detail}".strip())

    return parsed or FALLBACK_WRITES.get(sql_file, [])


def build_lineage_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    build_step_by_file = {step.sql_file: step for step in BUILD_STEPS}
    seen_files: set[str] = set()
    for sql_file in ACTIVE_SQL_FILES:
        if sql_file in seen_files:
            continue
        seen_files.add(sql_file)
        step = build_step_by_file.get(sql_file)
        writes = parse_write_targets(sql_file)
        rows.append(
            {
                "step": step.name if step else "",
                "sql_file": sql_file,
                "purpose": step.description if step else "",
                "writes": ", ".join(writes) if writes else "Unknown / inspect SQL manually",
            }
        )
    return rows


def generate_contract(
    consumer_tables: list[str],
    ops_tables: list[str],
    staging_tables: list[str],
    views: list[str],
    lineage_rows: list[dict[str, str]],
) -> str:
    supported_views = ordered_subset(views, SUPPORTED_VIEWS)
    compatibility_views = ordered_subset(views, COMPATIBILITY_VIEWS)

    lines: list[str] = []
    add = lines.append

    add(HEADER)
    add("# Profile Database Schema Contract\n\n")
    add(f"**Version:** `{SCHEMA_VERSION}`\n")
    add(
        f"**Datasets:** `bi-data-391216.{PRODUCTION_DATASET}`, "
        f"`bi-data-391216.{REBUILD_CANDIDATE_DATASET}`, "
        f"`bi-data-391216.{OPS_DATASET}`, "
        f"`bi-data-391216.{STAGING_DATASET}`\n"
    )
    add(
        f"**Effective shape:** `{len(consumer_tables)}` consumer/reference tables + "
        f"`{len(ops_tables)}` ops tables + `{len(staging_tables)}` staging helpers + "
        f"`{len(views)}` views\n"
    )
    add(
        "**Source of truth:** `shared/profile_database_manifest.py`, "
        "[sql/profile_database_ddl.sql](../sql/profile_database_ddl.sql), "
        "[sql/profile_database_views.sql](../sql/profile_database_views.sql), "
        "and active SQL `WRITES:` headers.\n\n"
    )
    add("---\n\n")
    add("## Contract Levels\n\n")
    add("1. `Consumer core`\nStable tables and views that downstream users should understand and query.\n")
    add("2. `Derived signals`\nUseful warehouse tables, but not the first consumer mental model.\n")
    add("3. `Reference`\nDictionaries and lookup/config support.\n")
    add("4. `Internal runtime`\nBuild logs, snapshots, restore diagnostics, and staging artifacts.\n\n")

    for group_name, preferred_tables in PHYSICAL_TABLE_GROUPS:
        group_tables = ordered_subset(consumer_tables, preferred_tables)
        if not group_tables:
            continue
        add(f"## {group_name}\n\n")
        add("| Table | Purpose |\n")
        add("|-------|---------|\n")
        for table in group_tables:
            add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
        add("\n")

    add("## Internal Runtime Tables (`profile_ops`)\n\n")
    add("| Table | Purpose |\n")
    add("|-------|---------|\n")
    for _, preferred_tables in OPS_TABLE_GROUPS:
        for table in ordered_subset(ops_tables, preferred_tables):
            add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
    add("\n")

    add("## Staging Helpers (`profile_staging`)\n\n")
    add("| Table | Purpose |\n")
    add("|-------|---------|\n")
    for table in staging_tables:
        add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
    add("\n")

    add("## Supported Views\n\n")
    add("| View | Support level | Purpose |\n")
    add("|------|---------------|---------|\n")
    for view in supported_views:
        support = "Default" if view == DEFAULT_CONSUMER_VIEW else "Supported"
        add(f"| `{view}` | {support} | {VIEW_DESCRIPTIONS.get(view, '')} |\n")
    add("\n")

    add("## Compatibility Views\n\n")
    add("| View | Purpose |\n")
    add("|------|---------|\n")
    for view in compatibility_views:
        add(f"| `{view}` | {VIEW_DESCRIPTIONS.get(view, '')} |\n")
    add("\n")

    add("## Active Write Paths\n\n")
    add("| Step | SQL file | Primary writes |\n")
    add("|------|----------|----------------|\n")
    for row in lineage_rows:
        add(f"| `{row['step']}` | `{row['sql_file']}` | {row['writes']} |\n")
    add("\n")

    add("## Column Rules\n\n")
    add("| Column | Rule |\n")
    add("|--------|------|\n")
    add("| `profile_updated_at` | Use on `profile_core` |\n")
    add("| `loaded_at` | Use on satellites, staging, and compatibility surfaces |\n")
    add("| `created_at` | Use for row creation timestamps where applicable |\n\n")

    add("## Process Notes\n\n")
    add("1. `rebuild` stages physical consumer/reference tables in `profile_data_candidate` and only publishes after gates pass.\n")
    add("2. `rebuild` and `refresh` now pin identity reads by copying `bn_id_xref`, `bn_id_hub`, and `bn_id_persistence` into `profile_staging` before SQL steps begin.\n")
    add("3. `refresh` is guarded for oversized scopes and short-circuits when the scope is empty.\n")
    add("4. `profile_consent` remains a compatibility surface, not the canonical consent fact model.\n")
    add("5. Legacy monolithic SQL files under `sql/legacy/profile_database/` are not the active build path.\n")

    return "".join(lines).rstrip() + "\n"


def generate_lineage(lineage_rows: list[dict[str, str]]) -> str:
    field_change_writers = [
        row for row in lineage_rows
        if "profile_ops.profile_field_changes" in row["writes"]
    ]

    lines: list[str] = []
    add = lines.append

    add(HEADER)
    add("# Profile Database Lineage\n\n")
    add("_Generated from the active SQL module `WRITES:` headers plus known runtime fallbacks._\n\n")
    add("| Step | SQL file | Purpose | Writes |\n")
    add("|------|----------|---------|--------|\n")
    for row in lineage_rows:
        add(
            f"| `{row['step']}` | `{row['sql_file']}` | {row['purpose']} | {row['writes']} |\n"
        )
    add("\n")

    add("## Field-Change Lineage Writers\n\n")
    if field_change_writers:
        add("| Step | SQL file |\n")
        add("|------|----------|\n")
        for row in field_change_writers:
            add(f"| `{row['step']}` | `{row['sql_file']}` |\n")
        add("\n")
    else:
        add("No active SQL modules currently advertise `profile_ops.profile_field_changes` in their `WRITES:` headers.\n")

    return "".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit non-zero if generated output differs from disk.")
    args = parser.parse_args()

    consumer_tables = parse_tables_for_dataset(PRODUCTION_DATASET)
    ops_tables = parse_tables_for_dataset(OPS_DATASET)
    staging_tables = flatten_grouped_items(STAGING_TABLE_GROUPS)
    views = parse_views()
    lineage_rows = build_lineage_rows()

    contract_content = generate_contract(
        consumer_tables=consumer_tables,
        ops_tables=ops_tables,
        staging_tables=staging_tables,
        views=views,
        lineage_rows=lineage_rows,
    )
    lineage_content = generate_lineage(lineage_rows)
    dictionary_content = _dictdoc.render(
        columns=parse_columns(DDL),
        lineage_rows=lineage_rows,
        header=HEADER,
        schema_version=SCHEMA_VERSION,
        production_dataset=PRODUCTION_DATASET,
        ops_dataset=OPS_DATASET,
        staging_dataset=STAGING_DATASET,
        table_descriptions=TABLE_DESCRIPTIONS,
        consumer_order=flatten_grouped_items(PHYSICAL_TABLE_GROUPS),
        ops_order=flatten_grouped_items(OPS_TABLE_GROUPS),
    )

    if args.check:
        existing_contract = CONTRACT_OUTPUT.read_text(encoding="utf-8") if CONTRACT_OUTPUT.exists() else ""
        existing_lineage = LINEAGE_OUTPUT.read_text(encoding="utf-8") if LINEAGE_OUTPUT.exists() else ""
        existing_dictionary = DICTIONARY_OUTPUT.read_text(encoding="utf-8") if DICTIONARY_OUTPUT.exists() else ""
        if (
            existing_contract != contract_content
            or existing_lineage != lineage_content
            or existing_dictionary != dictionary_content
        ):
            print("[FAIL] Schema contract, lineage, or data dictionary is stale. Re-run scripts/generate_schema_contract.py")
            return 1
        print("[OK] Schema contract, lineage, and data dictionary are up to date.")
        return 0

    CONTRACT_OUTPUT.write_text(contract_content, encoding="utf-8")
    LINEAGE_OUTPUT.write_text(lineage_content, encoding="utf-8")
    DICTIONARY_OUTPUT.write_text(dictionary_content, encoding="utf-8")
    print("[OK] Generated docs/PROFILE_DATABASE_SCHEMA_CONTRACT.md")
    print("[OK] Generated docs/PROFILE_DATABASE_LINEAGE.md")
    print("[OK] Generated docs/PROFILE_DATABASE_DATA_DICTIONARY.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
