#!/usr/bin/env python3
"""
Generate docs/PROFILE_DATABASE_OPERATOR_GUIDE.md from the shared manifest and
live SQL definitions.

Sources read:
  - shared/profile_database_manifest.py -> schema version, build modes, runtime layers
  - sql/profile_database_ddl.sql        -> physical profile_data tables
  - sql/profile_database_views.sql      -> views
  - docs/PROFILE_DATABASE_VERSION.md    -> version history
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from shared.profile_database_manifest import (  # noqa: E402
    BUILD_MODES,
    BUILD_STEPS,
    COMPATIBILITY_VIEWS,
    DEFAULT_CONSUMER_VIEW,
    FIELD_CHANGES_TRACKED_FIELDS,
    OPS_DATASET,
    OPS_TABLE_GROUPS,
    PHYSICAL_TABLE_GROUPS,
    PRODUCTION_DATASET,
    REBUILD_CANDIDATE_DATASET,
    SCHEMA_VERSION,
    STAGING_DATASET,
    STAGING_TABLE_GROUPS,
    SUPPORTED_VIEWS,
    TABLE_DESCRIPTIONS,
    VIEW_DESCRIPTIONS,
    VIEW_GROUPS,
    ordered_subset,
)


DDL = REPO_ROOT / "sql" / "profile_database_ddl.sql"
VIEWS_SQL = REPO_ROOT / "sql" / "profile_database_views.sql"
VERSION_MD = REPO_ROOT / "docs" / "PROFILE_DATABASE_VERSION.md"
OUTPUT = REPO_ROOT / "docs" / "PROFILE_DATABASE_OPERATOR_GUIDE.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_operator_guide.py - DO NOT EDIT BY HAND -->\n"
    "<!-- Re-generate: python scripts/generate_operator_guide.py -->\n"
    "<!-- CI should fail if this file is stale. -->\n\n"
)


def parse_tables_for_dataset(dataset: str) -> list[str]:
    src = DDL.read_text(encoding="utf-8")
    return [
        match.group(1)
        for match in re.finditer(
            rf"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+{re.escape(dataset)}\.(\w+)",
            src,
            re.IGNORECASE,
        )
    ]


def parse_views() -> list[str]:
    src = VIEWS_SQL.read_text(encoding="utf-8").replace("{view_dataset}", PRODUCTION_DATASET)
    return [
        match.group(1)
        for match in re.finditer(
            r"CREATE\s+OR\s+REPLACE\s+VIEW\s+profile_data\.(\w+)",
            src,
            re.IGNORECASE,
        )
    ]


def parse_version_rows() -> list[tuple[str, str, str]]:
    src = VERSION_MD.read_text(encoding="utf-8")
    rows = []
    row_re = re.compile(r"\|\s*(v\S+)\s*\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*(.+?)\s*\|")
    for match in row_re.finditer(src):
        rows.append((match.group(1), match.group(2), match.group(3).strip()))
    return rows


def generate(
    consumer_tables: list[str],
    ops_tables: list[str],
    staging_tables: list[str],
    views: list[str],
    version_rows: list[tuple[str, str, str]],
) -> str:
    step_sql = {step.name: step.sql_file for step in BUILD_STEPS}
    step_desc = {step.name: step.description for step in BUILD_STEPS}

    supported_views = ordered_subset(views, SUPPORTED_VIEWS)
    compatibility_views = ordered_subset(views, COMPATIBILITY_VIEWS)

    lines: list[str] = []
    add = lines.append

    add(HEADER)
    add(f"# Profile Database Operator Guide ({SCHEMA_VERSION})\n\n")
    add("_Generated from the current repo contract and SQL definitions._\n\n")

    add("## Quick Reference\n\n")
    add("| What | Value |\n")
    add("|------|-------|\n")
    add(f"| Schema version | `{SCHEMA_VERSION}` |\n")
    add(f"| Consumer dataset | `bi-data-391216.{PRODUCTION_DATASET}` |\n")
    add(f"| Rebuild candidate dataset | `bi-data-391216.{REBUILD_CANDIDATE_DATASET}` |\n")
    add(f"| Ops dataset | `bi-data-391216.{OPS_DATASET}` |\n")
    add(f"| Staging dataset | `bi-data-391216.{STAGING_DATASET}` |\n")
    add(f"| Consumer tables | {len(consumer_tables)} |\n")
    add(f"| Ops tables | {len(ops_tables)} |\n")
    add(f"| Staging helpers | {len(staging_tables)} |\n")
    add(f"| Views | {len(views)} |\n")
    add(f"| Default consumer surface | `profile_data.{DEFAULT_CONSUMER_VIEW}` |\n")
    add("| Rebuild command | `python orchestrate.py --source profile_database --env prod --build-mode rebuild` |\n")
    add("| Refresh command | `python orchestrate.py --source profile_database --env prod --build-mode refresh` |\n")
    add("| Re-enrich command | `python orchestrate.py --source profile_database --env prod --build-mode reenrich` |\n")
    add("| Release check | `python scripts/profile_release_check.py` |\n")
    add("| Schema contract generator | `python scripts/generate_schema_contract.py` |\n")
    add("| SQL validator | `python scripts/dry_run_profile_sql.py` |\n")
    add("| Persona validator | `python scripts/persona_snapshot_check.py` |\n\n")

    add("---\n\n")
    add("## Build Modes\n\n")
    add("| Mode | Steps | Description |\n")
    add("|------|-------|-------------|\n")
    mode_descriptions = {
        "rebuild": "Full rebuild from source. Use after identity-hub regeneration or schema changes.",
        "resume_rebuild": "Resume late-stage rebuild from existing candidate tables (restore, views, snapshot_core).",
        "resume_publish": "Resume candidate→production physical publish and view finalize only; reuse original `--execution-id`.",
        "refresh": "Daily lookback MERGE plus enrichment and view rebuild.",
        "reenrich": "Re-run enrich/personas on existing profile_core with no DDL or populate.",
        "views": "Rebuild views only.",
    }
    for mode, steps in BUILD_MODES.items():
        add(f"| `{mode}` | {len(steps)} | {mode_descriptions.get(mode, '')} |\n")
    add("\n")

    add("## Rebuild Steps\n\n")
    add("| Step | SQL file | Purpose |\n")
    add("|------|----------|---------|\n")
    for step in BUILD_MODES.get("rebuild", ()):
        add(f"| `{step}` | `{step_sql.get(step, '')}` | {step_desc.get(step, '')} |\n")
    add("\n")

    add("---\n\n")
    add("## Runtime Layers\n\n")
    add("The live project is intentionally split into a small consumer model plus internal runtime surfaces.\n\n")

    for group_name, preferred_tables in PHYSICAL_TABLE_GROUPS:
        group_tables = ordered_subset(consumer_tables, preferred_tables)
        if not group_tables:
            continue
        add(f"### {group_name} (`{PRODUCTION_DATASET}`)\n\n")
        add("| Table | Purpose |\n")
        add("|-------|---------|\n")
        for table in group_tables:
            add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
        add("\n")

    for group_name, preferred_tables in OPS_TABLE_GROUPS:
        group_tables = ordered_subset(ops_tables, preferred_tables)
        if not group_tables:
            continue
        add(f"### {group_name} (`{OPS_DATASET}`)\n\n")
        add("| Table | Purpose |\n")
        add("|-------|---------|\n")
        for table in group_tables:
            add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
        add("\n")

        if "profile_field_changes" in group_tables:
            add("#### Lineage coverage (`profile_field_changes`)\n\n")
            add(
                "This table is intentionally a **narrow audit log**, not a generic field-level history.\n"
                "Only the following fields are currently tracked for change lineage:\n\n"
            )
            add("| Tracked field |\n")
            add("|--------------|\n")
            for field in FIELD_CHANGES_TRACKED_FIELDS:
                add(f"| `{field}` |\n")
            add("\n")

    for group_name, preferred_tables in STAGING_TABLE_GROUPS:
        group_tables = ordered_subset(staging_tables, preferred_tables)
        if not group_tables:
            continue
        add(f"### {group_name} (`{STAGING_DATASET}`)\n\n")
        add("| Table | Purpose |\n")
        add("|-------|---------|\n")
        for table in group_tables:
            add(f"| `{table}` | {TABLE_DESCRIPTIONS.get(table, '')} |\n")
        add("\n")

    add("---\n\n")
    add("## View Surfaces\n\n")

    if supported_views:
        add("### Supported Consumer Views\n\n")
        add("| View | Purpose |\n")
        add("|------|---------|\n")
        for view in supported_views:
            marker = " **(DEFAULT)**" if view == DEFAULT_CONSUMER_VIEW else ""
            add(f"| `{view}`{marker} | {VIEW_DESCRIPTIONS.get(view, '')} |\n")
        add("\n")

    if compatibility_views:
        add("### Compatibility Views\n\n")
        add("These keep older query names working, but they are not the preferred design surface.\n\n")
        add("| View | Purpose |\n")
        add("|------|---------|\n")
        for view in compatibility_views:
            add(f"| `{view}` | {VIEW_DESCRIPTIONS.get(view, '')} |\n")
        add("\n")

    add("---\n\n")
    add("## Active SQL Layout\n\n")
    add("- Active runtime uses the split module files: `populate_*`, `fill_gaps_*`, `enrich_*`, `personas_*`.\n")
    add("- The shared runtime contract lives in `shared/profile_database_manifest.py`.\n")
    add("- Legacy monolithic SQL files may still exist in the repo for reference, but they are not the live build path and should not drive edits or onboarding.\n\n")

    add("---\n\n")
    add("## Release Checks\n\n")
    add("Current build acceptance checks gate publication of the consumer view layer. Rebuilds stage physical tables in `profile_data_candidate`, build candidate views in staging, run assertions there, then publish production views against the validated candidate dataset before promoting physical tables into `profile_data`. Refresh and re-enrich still update live production tables in place.\n\n")
    add("1. Build-local identity snapshots pin `bn_id_xref`, `bn_id_hub`, and `bn_id_persistence` so one run reads one consistent source image.\n")
    add("2. Refresh safety / parity sample\n")
    add("3. Orphan and parent-child integrity checks\n")
    add("4. Snapshot restore coverage\n")
    add("5. Fill-rate drift checks versus the latest completed baseline\n")
    add("6. Identity-hub manifest logging\n")
    add("7. Persona snapshot validation\n")
    add("8. Refresh-scope guard with empty-scope short-circuit and oversized-scope fail-fast\n")
    add("9. Soft performance checks for build duration regression, step hot-spot regressions, and refresh-scope efficiency\n")
    add("10. Runtime fingerprint + refresh-scope source breakdown logged to the ops layer for reproducibility\n")
    add("11. SQL module tests + generated schema/lineage docs in the local release check\n\n")

    add("---\n\n")
    add("## Failure playbook\n\n")
    add("This section is intentionally procedural. It exists so operators can recover from the most common failure modes without tribal knowledge.\n\n")
    add("### Release check fails (local)\n\n")
    add("- Run: `python scripts/profile_release_check.py`\n")
    add("- Fix the first failing check (SQL dry-run, scope audit, doc drift, or module tests).\n")
    add("- Re-run until it exits `0`.\n\n")
    add("### Preflight fails (identity hub not in expected state)\n\n")
    add("- Default action: **fix identity hub state**, then re-run `rebuild`.\n")
    add("- Override (only if you understand the risk): re-run with `--force`.\n\n")
    add("### Refresh scope is unexpectedly large (scope guard trips)\n\n")
    add("- Confirm the refresh-scope sources contract in `sql/profile_database_refresh_scope.sql`.\n")
    add("- Reduce lookback (or investigate the dominant source in ops logs) before forcing a large refresh.\n\n")
    add("### Refresh produces an empty scope (no-op)\n\n")
    add("- This is expected when no upstream changes were detected.\n")
    add("- Confirm the run status in `profile_release_status` / ops logs.\n\n")
    add("### Schema drift gate fails (profile_core type mismatch)\n\n")
    add("- The runtime hard-fails if `profile_core` has incompatible types.\n")
    add("- Fix the table definition (DDL / CTAS output) so it matches the contract, then re-run.\n\n")
    add("### Build fails mid-run (SQL step error)\n\n")
    add("- Identify the failing step in `profile_ops.profile_build_steps` (or `profile_build_log`).\n")
    add("- Fix the underlying SQL/module.\n")
    add("- Re-run the same build mode; for rebuilds that already staged candidate tables use `--build-mode resume_rebuild` where appropriate.\n\n")
    add("### Publish/promotion issues (rebuild)\n\n")
    add("- If view publication fails, re-run `--build-mode views`.\n")
    add("- If physical table promotion fails partway through, re-run **`--build-mode resume_publish`** with the **same** `--execution-id` as the failed run so `profile_ops.profile_publish_manifest` can skip tables already copied.\n")
    add("- If candidate tables or views are wrong, fix upstream and re-run `rebuild` or `resume_rebuild` as appropriate; do not use `resume_publish` to mask a bad candidate.\n\n")

    add("---\n\n")
    add("## Version History\n\n")
    add("| Version | Date | Highlights |\n")
    add("|---------|------|------------|\n")
    for version, date, highlights in version_rows:
        add(f"| {version} | {date} | {highlights} |\n")
    add("\n")

    add("---\n\n")
    add("## Runbook\n\n")
    add("### Full rebuild\n\n")
    add("```bash\n")
    add("python orchestrate.py --source profile_database --env prod --build-mode rebuild\n")
    add("python scripts/persona_snapshot_check.py\n")
    add("python scripts/dry_run_profile_sql.py\n")
    add("```\n\n")
    add("### Daily refresh\n\n")
    add("```bash\n")
    add("python orchestrate.py --source profile_database --env prod --build-mode refresh\n")
    add("```\n\n")
    add("### Re-enrich only\n\n")
    add("```bash\n")
    add("python orchestrate.py --source profile_database --env prod --build-mode reenrich\n")
    add("```\n\n")
    add("### Resume physical publish (after partial `publish_tables`)\n\n")
    add("```bash\n")
    add("python orchestrate.py --source profile_database --env prod --build-mode resume_publish --execution-id <original_build_id>\n")
    add("```\n")

    return "".join(lines)


def flatten_grouped_tables(groups: tuple[tuple[str, tuple[str, ...]], ...]) -> list[str]:
    ordered: list[str] = []
    for _, tables in groups:
        for table in tables:
            if table not in ordered:
                ordered.append(table)
    return ordered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the generated output differs from disk.")
    args = parser.parse_args()

    consumer_tables = parse_tables_for_dataset(PRODUCTION_DATASET)
    ops_tables = parse_tables_for_dataset(OPS_DATASET)
    staging_tables = flatten_grouped_tables(STAGING_TABLE_GROUPS)
    views = parse_views()
    version_rows = parse_version_rows()
    content = generate(consumer_tables, ops_tables, staging_tables, views, version_rows)

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print("[FAIL] Operator guide is stale. Re-run scripts/generate_operator_guide.py")
            return 1
        print("[OK] Operator guide is up to date.")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print("[OK] Generated docs/PROFILE_DATABASE_OPERATOR_GUIDE.md")
    print(f"  Schema version : {SCHEMA_VERSION}")
    print(f"  Consumer tables: {len(consumer_tables)}")
    print(f"  Ops tables     : {len(ops_tables)}")
    print(f"  Staging helpers: {len(staging_tables)}")
    print(f"  Views          : {len(views)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
