#!/usr/bin/env python3
"""Generate the identity hub data dictionary from the repo's own sources.

Output:
  - docs/IDENTITY_HUB_DATA_DICTIONARY.md

Sources of truth, all parsed rather than restated:
  - sql/identity_hub_ddl.sql   tables, columns, types, OPTIONS(description=)
  - configs/identity_hub.yaml  connectors, match rules, confidence, priorities
  - shared/identity_hub.py     connector methods, their source tables, run order

Usage:
    python scripts/generate_identity_hub_docs.py
    python scripts/generate_identity_hub_docs.py --check   # CI staleness gate
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts._hubparse import (  # noqa: E402
    connector_config,
    parse_connectors,
    parse_ddl,
    parse_run_order,
)

DDL = REPO_ROOT / "sql" / "identity_hub_ddl.sql"
CONFIG = REPO_ROOT / "configs" / "identity_hub.yaml"
HUB_PY = REPO_ROOT / "shared" / "identity_hub.py"
OUTPUT = REPO_ROOT / "docs" / "IDENTITY_HUB_DATA_DICTIONARY.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_identity_hub_docs.py - DO NOT EDIT BY HAND -->\n"
    "<!-- Re-generate: python scripts/generate_identity_hub_docs.py -->\n\n"
)

INTRO = """
Every table in `identity_hub_data`: what it holds, every column with its type
and definition, and which connector produces the rows.

**How the hub is populated.** Connectors run in a fixed order (section 2). Each
one reads a source system, finds two identifiers that belong to the same person,
and emits an **edge** into `bn_id_hub` tagged with a `match_rule` and a
confidence. After every connector has run, union-find collapses the edge set into
connected components; each component becomes one `bn_id`, and the
identifier-to-`bn_id` mapping is published to `bn_id_xref`. Everything else in
the dataset is either an audit trail of that process or a debugging surface over
it.

**Where to start.** `bn_id_xref` is the consumer surface -- one row per
identifier, carrying the `bn_id` it resolved to. Join to it from any system that
knows an email, cookie or user id. `bn_id_neighbors` answers "why are these two
the same person". The rest is machinery.
"""

SPECIAL = {
    "bn_id_xref": [
        "`identifier_value` is normalised on write: emails lowercased and trimmed, "
        "`wp_user_id` site-qualified as `{site}:{id}` because WordPress reuses "
        "numeric ids across sites. Join on the normalised form or you will miss rows.",
        "`cluster_tier` is the single most important filter. `tier1` clusters "
        "contain a durable anchor (email, SSO key, NPI) and are real people; "
        "`tier2` clusters are cookie-only and are closer to browsers than humans.",
        "`is_bot`, `is_suspicious` and `is_shared_workstation` are advisory flags, "
        "not filters. Nothing removes those rows for you.",
    ],
    "bn_id_hub": [
        "Append-only. Edges are retired by setting `is_active = FALSE`, never deleted, "
        "so an unfiltered `COUNT(*)` includes history.",
        "Three confidence columns, and they are not interchangeable. "
        "`base_confidence` is one observation, `confidence` aggregates repeated "
        "observations, and `effective_confidence` applies time decay. "
        "**Only edges with `effective_confidence >= 0.80` actually stitch.**",
        "`bn_id` is the cluster the edge ended up in *after* union-find. It is an "
        "output, not an input -- do not read it as 'the connector assigned this'.",
        "`first_seen` feeds `profile_core.source_created_at` for an allowlist of "
        "`match_rule` values. Rules not on that list are pipeline-stamped at build "
        "time and would silently corrupt acquisition dates.",
    ],
    "bn_id_persistence": [
        "Redirect registry for retired ids. When two clusters merge, the losing "
        "`bn_id` gets a row here pointing at the survivor, so old references still "
        "resolve.",
        "**`event_type` is written as `MERGE`, and the registry holds redirects "
        "only.** For the full merge/split history query `bn_id_identity_changes` "
        "instead.",
    ],
    "bn_id_neighbors": [
        "The cross-product of identifiers inside each cluster, so it is the largest "
        "table in the dataset and grows quadratically with cluster size. Always "
        "filter by `bn_id`.",
        "`match_rule` here is the answer to 'why are these two linked' -- the "
        "fastest way to debug a suspicious merge.",
    ],
    "bn_id_node_index": [
        "One snapshot per run, including nodes that never reached `bn_id_xref`. "
        "**Filter to `bn_id_manifest.active_run_id`** or you will read several runs "
        "at once and multiply your counts.",
    ],
    "bn_id_metrics": [
        "Long format: one row per (`run_id`, `metric_name`), values in a single "
        "`FLOAT64` column shared by counts and durations.",
    ],
    "bn_id_manifest": [
        "The pointer to the run downstream consumers should read. Anything that "
        "reads `bn_id_node_index` or `bn_id_metrics` should join here first.",
    ],
    "bn_id_identity_changes": [
        "The real merge/split audit trail. `SPLIT` means a sub-cluster broke off and "
        "took `retired_bn_id` as its new identity, so 'retired' does not always mean "
        "'gone'.",
    ],
}


def render(tables, connectors, run_order, conn_cfg, hub_cfg) -> str:
    out = [HEADER, "# Identity Hub Data Dictionary\n\n"]
    add = out.append
    add("**Dataset:** `bi-data-391216.identity_hub_data`\n")
    add("**Generated from:** [sql/identity_hub_ddl.sql](../sql/identity_hub_ddl.sql), ")
    add("[configs/identity_hub.yaml](../configs/identity_hub.yaml), ")
    add("[shared/identity_hub.py](../shared/identity_hub.py)\n")
    add(INTRO)
    add("\n---\n\n## 1. Tables\n\n")
    add("| Table | Columns | Purpose |\n|---|---:|---|\n")
    for key, meta in tables.items():
        name = key.split(".", 1)[1]
        add(
            f"| [`{name}`](#{name}) | {len(meta['columns'])} | {meta['comment'][:110]} |\n"
        )

    # ── run order ──
    add("\n---\n\n## 2. How rows get made: connector run order\n\n")
    add(
        "Each connector emits edges into `bn_id_hub`. They run in this order, and "
        "order matters -- later connectors can only merge clusters the earlier ones "
        "created.\n\n"
    )
    add("| # | Phase | Connector | Match rules | Reads |\n|---:|---|---|---|---|\n")
    for i, (phase, method) in enumerate(run_order, 1):
        info = connectors.get(method, {})
        rules = ", ".join(f"`{r}`" for r in info.get("match_rules", [])) or "--"
        srcs = ", ".join(f"`{t}`" for t in info.get("source_tables", [])[:3]) or "--"
        add(f"| {i} | {phase} | `{method}` | {rules} | {srcs} |\n")

    # ── connector settings ──
    add("\n### Connector settings (from `identity_hub.yaml`)\n\n")
    add(
        "| Connector | Enabled | Type | Confidence | Match rule |\n|---|---|---|---:|---|\n"
    )
    for name, cfg in sorted(conn_cfg.items()):
        if not isinstance(cfg, dict):
            continue
        add(
            f"| `{name}` | {cfg.get('enabled', '--')} | {cfg.get('link_type', '--')} "
            f"| {cfg.get('confidence', '--')} | `{cfg.get('match_rule', '--')}` |\n"
        )

    # ── identifier priorities ──
    prio = (hub_cfg or {}).get("source_priorities") or {}
    if prio:
        add("\n### Identifier priority (lower wins when picking a cluster root)\n\n")
        add("| Priority | Identifier |\n|---:|---|\n")
        for ident, rank in sorted(prio.items(), key=lambda kv: (kv[1], kv[0])):
            add(f"| {rank} | `{ident}` |\n")

    # ── columns ──
    add("\n---\n\n## 3. Columns\n\n")
    for key, meta in tables.items():
        name = key.split(".", 1)[1]
        add(f"### {name}\n\n")
        if meta["comment"]:
            add(f"{meta['comment']}\n\n")
        add("| Column | Type | Req | Definition |\n|---|---|---|---|\n")
        for col in meta["columns"]:
            req = "yes" if col["required"] else ""
            desc = col["desc"].replace("|", "\\|") or "--"
            add(f"| `{col['name']}` | `{col['type']}` | {req} | {desc} |\n")
        notes = SPECIAL.get(name)
        if notes:
            add("\n**Special:**\n\n")
            for n in notes:
                add(f"- {n}\n")
        add("\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit non-zero if stale")
    args = ap.parse_args()

    cfg = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    hub_cfg = cfg.get("identity_hub", cfg)
    content = render(
        parse_ddl(DDL),
        parse_connectors(HUB_PY),
        parse_run_order(HUB_PY),
        connector_config(cfg),
        hub_cfg,
    )

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            print(
                "[FAIL] Identity hub data dictionary is stale. Re-run scripts/generate_identity_hub_docs.py"
            )
            return 1
        print("[OK] Identity hub data dictionary is up to date.")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
